### ISSUE TITLE
daemonSet 类型自动结束

### ISSUE THREAD

**Issue by pineking** [typhoonzero/GPUMon#3]
运行 `kubectl create -f gpumon-daemonset.yaml`， daemonSet 运行十几秒后退出，原因未知，但是以 Pod 的类型运行，则正常，可以稳定的运行。

gpumon-daemonset.yaml 内容如下：
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: gpumon
  labels:
    kubernetes.io/cluster-service: "true"
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: gpumon
    spec:
      nodeSelector:
        gpu: "y"
      containers:
      - name: gpumon
        securityContext:
          privileged: true
        image: bootstrapper:5000/pineking/gpumon
        env:
        - name: INFLUXDB_ADDR
          value: http://monitoring-influxdb:8086/
        volumeMounts:
          - mountPath: /usr/bin/nvidia-smi
            name: nvidia-smi
          - mountPath: /usr/lib64
            name: nvidia-libs
      volumes:
      # FIXME: must mount nvidia-smi binary and nvidia libs
      - name: nvidia-smi
        hostPath:
          path: /usr/bin/nvidia-smi
      - name: nvidia-libs
        hostPath:
          path: /usr/local/nvidia/lib64
```

执行 `kubectl create -f gpumon-daemonset.yaml` 后：

```
 atlas@bootstrapper  ~/liuqs/gpumon  kubectl get ds -o wide --all-namespaces -a
NAMESPACE     NAME      DESIRED   CURRENT   READY     NODE-SELECTOR   AGE       CONTAINER(S)   IMAGE(S)                            SELECTOR
kube-system   gpumon    1         1         1         gpu=y           16s       gpumon         bootstrapper:5000/pineking/gpumon   app=gpumon
 atlas@bootstrapper  ~/liuqs/gpumon  kubectl describe ds gpumon --namespace=kube-system
Name:           gpumon
Image(s):       bootstrapper:5000/pineking/gpumon
Selector:       app=gpumon
Node-Selector:  gpu=y
Labels:         kubernetes.io/cluster-service=true
Desired Number of Nodes Scheduled: 1
Current Number of Nodes Scheduled: 1
Number of Nodes Misscheduled: 0
Pods Status:    1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Events:
  FirstSeen     LastSeen        Count   From            SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----            -------------   --------        ------                  -------
  21s           21s             1       {daemon-set }                   Normal          SuccessfulCreate        Created pod: gpumon-mv298
```

十几秒后，daemonset 消失：

```
 atlas@bootstrapper  ~/liuqs/gpumon  kubectl get ds -o wide --all-namespaces -a
No resources found.
```

但是，以 Pod 类型运行，能稳定运行， yaml 文件如下：
```
apiVersion: v1
kind: Pod
metadata:
  name: gpumon
  labels:
    kubernetes.io/cluster-service: "true"
  namespace: kube-system
spec:
      containers:
      - name: gpumon
        securityContext:
          privileged: true
        image: bootstrapper:5000/pineking/gpumon
        env:
        - name: INFLUXDB_ADDR
          value: http://monitoring-influxdb:8086/
        volumeMounts:
          - mountPath: /usr/bin/nvidia-smi
            name: nvidia-smi
          - mountPath: /usr/lib64
            name: nvidia-libs
      volumes:
      # FIXME: must mount nvidia-smi binary and nvidia libs
      - name: nvidia-smi
        hostPath:
          path: /usr/bin/nvidia-smi
      - name: nvidia-libs
        hostPath:
          path: /usr/local/nvidia/lib64
      nodeName: 00-1b-21-bc-36-58
```
